# Generated by Django 2.1.2 on 2018-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fall', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
